name: RadioPlugin
main: io.github.LilParker.RadioPlugin.RadioPlugin
version: 0.1
author: Lil_Parker

commands:
  setfreq:
    description: Set your radio frequency
    
  getfreq:
    description: Get your current frequency
    
  radio:
    description: Send a message on your current frequency
    aliases: r