name: RadioPlugin
main: io.github.LilParker.RadioPlugin.RadioPlugin
version: 1
authors: [Lil_Parker, Jet_Fusion]
depends: [Essentials]

commands:
  setfreq:
    description: Set your radio frequency
    usage: /sefreq (frequency)
    
  getfreq:
    description: Get your current frequency
    usage: /getfreq
    
  radio:
    description: Send a message on your current frequency
    usage: /r (message)
    aliases: r
    
  setekey:
    description: Set your radio encryption key. Use "/setekey" clear to clear your encription key.
    usage: /setekey (key)
  
  getekey:
    description: Get your current encryption key
    usage: /getekey
    
  settag:
    description: Set your radio tag
    usage: /settag (tag)
    
  gettag:
    description: Get your current radio tag
    usage: /gettag
    
  setvol:
    description: Set your radio's volume. Must be a interger (No decimal)
    usage: /setvol (volume)
    
  getvol:
    description: Get your radio's current volume
    usage: /getvol